name: Development - Supabase Deploy

on:
  push:
    branches:
      - development
    paths:
      - apps/supabase/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: apps/supabase/

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID

      - run: supabase db push --include-all
