name: development - apps/supabase seed images

on:
  workflow_dispatch

jobs:
  supabase_reset:
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: apps/supabase/

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

        # id: seed-images
        # with:
        #   milliseconds: 10000

      - run: pnpm install

      - run: pnpm run generate-images
      # - uses: supabase/setup-cli@v1
      #   with:
      #     version: latest
      #
      # - run: supabase link --project-ref $PROJECT_ID
      #
      # - run: supabase db reset --linked --debug
